name: Deploy Fit360

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts


      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Copy Repository to Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/fit360 || exit
            git reset --hard
            git pull origin main
          EOF

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
